### ISSUE TITLE
Исправить подключение к редис

### ISSUE THREAD

**Issue by Berupor** [Berupor/Movies-Together#52]
[Тут](https://github.com/Berupor/Movies-Together/blob/main/chat_service/src/main.py#L36) при каждом новом подключению к чату открывается новое соединения к редису, что может создать оверхед на поддержку этих соединений и в целом превысить количество доступных соединений. Нужно либо использовать одно соединение как сделано в aggregator_service, либо использовать connection pool

**Comment by NikitaTheGeneral** [comment]
готово
